<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use function route;

class Company extends Model
{
	protected $fillable = array(
		'name',
		'description',
		'user_id',
		'address',
		'city',
		'prov',
		'country',
		'tel',
		'fax',
		'email',
		'pec',
		'skype',
		'website',
		'contactName',
		'vatCode',
		'cfCode',
	);


	/**
	 * A company belongs to:
	 * - user
	 */
	public function user()
	{
		return $this->belongsTo('App\User');
	}

	/**
	 * A company has many projects
	 */
	public function projects()
	{
		return $this->hasMany("App\Project");
	}

	/**
	 * A company has many credits
	 */
	public function credits()
	{
		return $this->hasMany("App\CompanyCredit");
	}


	public function comments()
	{
		return $this->morphMany('App\Comment', 'commentable');
	}

	public function files()
	{
		return $this->morphMany('App\File', 'uploadable');
	}

	public function delete()
	{
		//Delete comments
		$this->comments()->delete();

		return parent::delete(); // TODO: Change the autogenerated stub
	}

	public function getContactMail()
	{
		return $this->email;
	}

	public function getViewRoute()
	{
		return route('companies.show', ['company_id' => $this->id]);
	}

}
