<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{

	protected $fillable = array(
		'name',
		'description',
		'company_id',
		'user_id',
		'days',
	);

	/**
	 * A project belongs to:
	 * - user (many)
	 * - company
	 */
	public function user()
	{
		return $this->belongsToMany('App\User');
	}

	public function company()
	{
		return $this->belongsTo('App\Company');
	}

	/**
	 * Count how many task are on project
	 *
	 * @param int|null $status_id
	 *
	 * @return mixed
	 */
	public function tasks($status_id = null)
	{
		if(!empty($status_id)) {
			return $this->hasMany('App\Task')->where(['status_id' => $status_id])->get();
		}
		return $this->hasMany('App\Task');
	}

	/**
	 * Count how many task are on project
	 *
	 * @param int|null $status_id
	 *
	 * @return mixed
	 */
	public function tasks_count($status_id = null)
	{
		$data = ['project_id' => $this->id];
		if($status_id !== null) {
			$data['status_id'] = $status_id;
		}
		$res = Task::where($data)->count();
		return $res;
	}


	/**
	 * A project belongs to many users
	 * Laravel search for a Model named ProjectUser
	 */
	public function users()
	{
		return $this->belongsToMany("App\User");
	}



	public function comments()
	{
		return $this->morphMany('App\Comment', 'commentable');
	}


	public function delete()
	{
		//Delete comments
		$this->comments()->delete();

		return parent::delete(); // TODO: Change the autogenerated stub
	}

	public function getContactMail()
	{
		return $this->company->getContactMail();
	}

	public function getViewRoute()
	{
		return route('projects.show', ['project_id' => $this->id]);
	}
}
