<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
	protected $fillable = array(
		'name',
		'description',
		'status_id',
		'project_id',
		'user_id',
		'company_id',
		'days',
		'hours',
	);



	/**
	 * A task belongs to:
	 * - user
	 * - project
	 * - company
	 */
	public function user()
	{
		return $this->belongsTo('App\User');
	}

	public function project()
	{
		return $this->belongsTo('App\Project');
	}

	public function company()
	{
		return $this->belongsTo('App\Company');
	}

	public function status()
	{
		return $this->belongsTo('App\TaskStatus');
	}

	/**
	 * A task belongs to many users
	 * Laravel search for a Model named TaskUser
	 */
	public function users()
	{
		return $this->belongsToMany("App\User");
	}


	public function comments()
	{
		return $this->morphMany("App\Comment", "commentable");
	}

	public function delete()
	{
		//Delete comments
		$this->comments()->delete();

		return parent::delete(); // TODO: Change the autogenerated stub
	}

	public function getContactMail()
	{
		return $this->company->getContactMail();
	}

	public function getViewRoute()
	{
		return route('tasks.show', ['task_id' => $this->id]);
	}
}
