<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
	    'first_name',
	    'middle_name',
	    'last_name',
	    'email',
	    'password',
	    'city',
		'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function fullName()
    {
    	return $this->first_name." ".$this->last_name;
    }

    /*
     * User can has many:
     * - companies
     */
	public function companies()
	{
		return $this->hasMany('App\Company');
	}


	/**
	 * The user belong to a role
	 */
	public function role()
	{
		return $this->belongsTo('App\Role');
	}


	/**
	 * A user belongs to many tasks
	 * Laravel search for a Model named TaskUser
	 */
	public function tasks()
	{
		return $this->belongsToMany("App\Task");
	}

	/**
	 * A user belongs to many projects
	 * Laravel search for a Model named ProjectUser
	 */
	public function projects()
	{
		return $this->belongsToMany("App\Project");
	}


	public function comments()
	{
		return $this->morphToMany("App\Comment", "commentable");
	}

	public function delete()
	{
		//Delete comments
		$this->comments()->delete();

		return parent::delete(); // TODO: Change the autogenerated stub
	}
}
