<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Laravel\Passport\HasApiTokens;
use function asset;
use function base64_encode;
use function md5;

class User extends Authenticatable
{
    use Notifiable;
    use HasApiTokens;

    const AVATAR_FOLDER = "avatars";

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
	    'first_name',
	    'middle_name',
	    'last_name',
	    'email',
	    'password',
	    'city',
		'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function fullName()
    {
    	$fullName = trim($this->first_name." ".$this->last_name);
    	return (empty($fullName)) ? $this->email : $fullName;
    }

    public function __toString()
    {
	    return $this->fullName();
    }


    public function avatar()
    {
        if(Storage::exists(self::AVATAR_FOLDER."/".md5($this->id).".jpeg")) {
            return "data:image/jpeg;base64, ".base64_encode(Storage::get(self::AVATAR_FOLDER."/".md5($this->id).".jpeg"));
        }
        return asset("images/no-profile.png");
    }

	/*
	 * User can has many:
	 * - companies
	 */
	public function companies()
	{
		return $this->hasMany('App\Company');
	}


	/**
	 * The user belong to a role
	 */
	public function role()
	{
		return $this->belongsTo('App\Role');
	}


	/**
	 * A user belongs to many tasks
	 * Laravel search for a Model named TaskUser
	 */
	public function tasks()
	{
		return $this->belongsToMany("App\Task");
	}

	/**
	 * A user belongs to many projects
	 * Laravel search for a Model named CustomerProject
	 */
	public function projects()
	{
		return $this->belongsToMany("App\Project");
	}

	public function assigned_projects()
    {
        return \App\Project::where("user_id", $this->id);
    }

    /**
     * @return \App\Task array
     */
    public function assigned_tasks(array $task_status_ids = null, $group_by = false, $project_id = 0)
    {
        if(empty($task_status_ids)) {
            //$where_ids = " (".implode(",", $task_status_ids).") ";
            $task_status_ids = [1];// TaskStatus::getIds();
        }

        if($group_by) {
            return \App\Task::where("project_id", ($project_id > 0) ? "=" : ">", $project_id)
                ->where(function($query) use ($task_status_ids) {

                    $query->where("user_id", $this->id);
                    $query->whereIn("status_id", $task_status_ids);
                    $query->whereIn("id", function ($query) {
                            $query->select("task_id")
                                ->from("task_user")
                                ->where("user_id", $this->id);
                        }, "or");

                })
                ->groupBy("status_id")
                ->get(['*', DB::raw('count(tasks.id) as totals')]);
        }
        else {
            return \App\Task::where("project_id", ($project_id > 0) ? "=" : ">", $project_id)
                ->where(function($query) use ($task_status_ids) {
                    $query->where("user_id", $this->id);
                    $query->whereIn("status_id", $task_status_ids);
                    $query->whereIn("id", function ($query) {
                            $query->select("task_id")
                                ->from("task_user")
                                ->where("user_id", $this->id);
                        }, "or");
                });

        }
    }


	public function comments()
	{
		return $this->morphToMany("App\Comment", "commentable");
	}


	/**
	 * A user could have many customers
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function customers()
	{
		return $this->hasMany("App\Customer");
	}


	public function delete()
	{
		//Delete comments
		$this->comments()->delete();

		//Delete customers
		$this->customers()->delete();

		return parent::delete(); // TODO: Change the autogenerated stub
	}
}
